---
- name: Demonstrating the debug module
  hosts: planetexpress
  connection: ansible.builtin.ssh
  gather_facts: true # audit the systems we are connecting to

  tasks:

    - name: Display a simple debug message
      ansible.builtin.debug:
        msg: "Hello from the debug module! Ansible is running smoothly."

    - name: Show the default IPv4 address for each host
      ansible.builtin.debug:
        var: ansible_default_ipv4.address       # this is from gather_facts. var and msg are mutually exclusive within debug

